# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
# Pinned SHAs for CI sibling checkout and git `workspace.dependencies` (W-62 / Dependabot).

[umst-foundations]
sha = "85bda074c1a34788f60210d09c15e22ac76b0e74"
repo = "https://github.com/tytolabs/umst-foundations"

[umst-cartridge-api]
sha = "cfb27d2efad3f458dc5ac3d55581ef81f86a6705"
repo = "https://github.com/tytolabs/umst-cartridge-api"

[umst-cartridges]
sha = "ab87088303320452643e6743c0e4bafb2f899827"

[umst-semantics]
sha = "6f7f5bef678ef2526d5763efe2ff3fabfde6e800"
repo = "https://github.com/tytolabs/umst-semantics"

[umst-manifold]
sha = "575d9508f872e6c5ae3d5fc9fe3bfcb1f44d5ab1"
repo = "https://github.com/tytolabs/umst-manifold"

[umst-ucrs]
sha = "a1202338638241749daa226855f682fd73f8f872"
repo = "https://github.com/tytolabs/umst-ucrs"
repo = "https://github.com/tytolabs/umst-cartridges"

[umst-chem]
sha = "7c36bd71fe1645fc8f21405fb743be7d2635ad7a"
repo = "https://github.com/tytolabs/umst-chem"

[umst-cartridge-registry]
sha = "ea69af507c4930abd51b6359d480dda60964b74a"
repo = "https://github.com/tytolabs/umst-cartridge-registry"
