# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
# Pinned SHAs for CI sibling checkout and git `workspace.dependencies` (W-62 / Dependabot).

[umst-foundations]
sha = "85bda074c1a34788f60210d09c15e22ac76b0e74"
repo = "https://github.com/tytolabs/umst-foundations"

[umst-cartridge-api]
sha = "4adbc3f618f89a6826ed986536f94330c4e26840"
repo = "https://github.com/tytolabs/umst-cartridge-api"

[umst-cartridges]
sha = "47ae0cbd3a44bcbfe14cdb7b92eb6791ffd9187a"
repo = "https://github.com/tytolabs/umst-cartridges"

[umst-chem]
sha = "6db9510ee6f6e8e5ecc68127f662258f4c72ec2b"
repo = "https://github.com/tytolabs/umst-chem"

[umst-cartridge-registry]
sha = "ea69af507c4930abd51b6359d480dda60964b74a"
repo = "https://github.com/tytolabs/umst-cartridge-registry"

[umst-semantics]
sha = "6f7f5bef678ef2526d5763efe2ff3fabfde6e800"
repo = "https://github.com/tytolabs/umst-semantics"

[umst-manifold]
sha = "71e1688d4a30699a3463a9856646157540a3f52b"
repo = "https://github.com/tytolabs/umst-manifold"

[umst-ucrs]
sha = "a1202338638241749daa226855f682fd73f8f872"
repo = "https://github.com/tytolabs/umst-ucrs"

[umst-supercap-cartridge]
sha = "f8d2675df39a69408614988d45166e57ce0188bb"
repo = "https://github.com/tytolabs/umst-supercap-cartridge"
