# SPDX-License-Identifier: MIT
"""Manual stubs for `_umst_concrete_cartridge` native module."""

from typing import Any, List, Optional

def predict(
    spec: Any,
    *,
    profile: str = ...,
    schema_version: str = ...,
) -> dict[str, Any]: ...
def audit(profile: str, csv_text: str, limit: Optional[int] = ...) -> dict[str, Any]: ...
def certify(profile: str) -> dict[str, Any]: ...
def schema(kind: str) -> str: ...
def bundled_profile_ids() -> List[str]: ...
def canonical_json(obj: Any) -> bytes: ...
