// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Santhosh Shyamsundar, Santosh Prabhu Shenbagamoorthy — Studio TYTO

use burn::tensor::{backend::Backend, Tensor};

/// Pure tensor implementation of the Fiber Reinforcement Engine.
/// Computes multiscale micromechanical pullout, debonding, and macroscopic crack bridging.
pub struct FiberEngine<B: Backend> {
    _backend: std::marker::PhantomData<B>,
}

impl<B: Backend> FiberEngine<B> {
    /// Computes cutting-edge fiber pullout mechanics and crack bridging.
    /// This enhances the Fracture Toughness (K_Ic) generated by the FractureEngine.
    ///
    /// # Arguments
    /// * `fiber_vol_fraction` (V_f) - Volume fraction of fibers [Batch, Depth, Height, Width]
    /// * `fiber_aspect_ratio` (L/d) - Aspect ratio of the fibers [Batch, Depth, Height, Width]
    /// * `fiber_tensile_strength` - Ultimate tensile strength of the fiber (MPa)
    /// * `matrix_strength` - Surrounding cementitious matrix compressive strength (MPa)
    pub fn compute_micromechanics(
        fiber_vol_fraction: Tensor<B, 4>,
        fiber_aspect_ratio: Tensor<B, 4>,
        fiber_tensile_strength: Tensor<B, 4>,
        matrix_strength: Tensor<B, 4>,
    ) -> (Tensor<B, 4>, Tensor<B, 4>, Tensor<B, 4>) {
        // 1. Interfacial Bond Strength (tau)
        // τ ≈ 0.6 × √(f'c) for good matrix adhesion
        let tau_bond = matrix_strength.clone().sqrt().mul_scalar(0.6_f32);

        // Orientation factor (3D random) & Length efficiency
        let eta_theta = 0.5_f32;
        let eta_l = 0.8_f32; // Assuming high bond efficiency before complete pullout

        // 2. Tensile Strength Enhancement (Naaman & Reinhardt)
        // Δσ_t = η_θ × η_l × V_f × τ × (L/d)
        let tensile_boost = fiber_vol_fraction
            .clone()
            .mul(tau_bond.clone())
            .mul(fiber_aspect_ratio.clone())
            .mul_scalar(eta_theta * eta_l);

        // 3. Cohesive Zone Model (CZM) Fracture Energy Boost (G_f_boost)
        // Integrating the frictional sliding pullout curve:
        // G_f_fiber = V_f * L_f * τ * η_θ / (2 * d_f)
        // This acts as a massive multiplier for post-cracking ductility.
        // Simplified proportionality: G_f_boost ∝ V_f * (L/d) * τ
        let fracture_energy_boost = fiber_vol_fraction
            .clone()
            .mul(fiber_aspect_ratio.clone())
            .mul(tau_bond.clone())
            .mul_scalar(eta_theta * 0.5_f32); // Scaling factor for sliding dissipation

        // 4. Ultimate Crack Bridging Stress (Fib Model Code 2010)
        // σ_bridge = 0.45 × σ_f × V_f × (L/d) × η_θ
        let bridging_stress = fiber_tensile_strength
            .clone()
            .mul(fiber_vol_fraction.clone())
            .mul(fiber_aspect_ratio.clone())
            .mul_scalar(0.45_f32 * eta_theta);

        // Filter out zero-fiber regions to prevent floating point anomalies
        let active_fiber_mask = fiber_vol_fraction.greater_elem(0.001_f32);

        let final_tensile_boost =
            tensile_boost.mask_fill(active_fiber_mask.clone().bool_not(), 0.0_f32);
        let final_gf_boost =
            fracture_energy_boost.mask_fill(active_fiber_mask.clone().bool_not(), 0.0_f32);
        let final_bridging = bridging_stress.mask_fill(active_fiber_mask.bool_not(), 0.0_f32);

        (final_tensile_boost, final_gf_boost, final_bridging)
    }
}
