#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Santhosh Shyamsundar, Santosh Prabhu Shenbagamoorthy — Studio TYTO
"""S2: generate TOOL_CONTRACTS fragment from tools_v1 manifest snapshot.

Hand-authored docs/TOOL_CONTRACTS.md remains SSOT until this generator matches it
exactly (cutover USER-gated). This script:
  - emits a generated fragment (default)
  - --check: asserts all 13 tool names appear in the hand SSOT with 7-field tables,
    generated names ⊆ hand names, and no Proposed tool names are shipped.

Usage:
  python3 scripts/gen_tool_contracts.py
  python3 scripts/gen_tool_contracts.py --check
  python3 scripts/gen_tool_contracts.py --out docs/TOOL_CONTRACTS.generated.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "crates/umst-mcp/src/manifest/tools_v1_schema.json"
HAND = ROOT / "docs/TOOL_CONTRACTS.md"
DEFAULT_OUT = ROOT / "docs/TOOL_CONTRACTS.generated.md"

SEVEN_FIELDS = (
    "Pre",
    "Post",
    "Errors",
    "Idempotent",
    "SideEffectClass",
    "Cost",
    "Provenance",
)

# Align with S1 SideEffectClass + hand doc aliases (EpistemicMutating / Pure / Session).
SIDE_EFFECT = {
    "umst_contribute": "EpistemicMutating",
    "umst_transition_propose": "EpistemicMutating",
    "umst_arena_open": "EpistemicMutating",
    "umst_arena_close": "EpistemicMutating",
    "umst_profiles": "Pure",
    # remaining → ReadOnly
}

PROPOSED_FORBIDDEN = (
    "umst_dry_run",
    "umst_promote_contribution",
    "umst_arena_session",
)


def side_effect(name: str) -> str:
    return SIDE_EFFECT.get(name, "ReadOnly")


def load_tools() -> list[dict]:
    data = json.loads(SCHEMA.read_text())
    tools = data["tools"]
    assert len(tools) == 13, f"expected 13 tools, got {len(tools)}"
    return sorted(tools, key=lambda t: t["name"])


def required_keys(tool: dict) -> list[str]:
    req = tool.get("inputSchema", {}).get("required") or []
    return sorted(str(x) for x in req)


def render_fragment(tools: list[dict]) -> str:
    lines = [
        "<!-- GENERATED by scripts/gen_tool_contracts.py — do not hand-edit -->",
        "<!-- Hand SSOT remains docs/TOOL_CONTRACTS.md until S2 cutover (USER-gated). -->",
        "",
        "# MCP tool contracts (generated fragment)",
        "",
        "Source: `crates/umst-mcp/src/manifest/tools_v1_schema.json` + SideEffectClass map.",
        "",
    ]
    for t in tools:
        name = t["name"]
        req = required_keys(t)
        pre = (
            f"Required args: {', '.join(f'`{k}`' for k in req)}"
            if req
            else "No required args"
        )
        lines.extend(
            [
                f"## `{name}`",
                "",
                "| Field | Contract |",
                "|:---|:---|",
                f"| Pre | {pre} |",
                "| Post | See hand `TOOL_CONTRACTS.md` SSOT |",
                "| Errors | See hand `TOOL_CONTRACTS.md` SSOT |",
                "| Idempotent | See hand `TOOL_CONTRACTS.md` SSOT |",
                f"| SideEffectClass | {side_effect(name)} |",
                "| Cost | See hand `TOOL_CONTRACTS.md` SSOT |",
                "| Provenance | See hand `TOOL_CONTRACTS.md` SSOT |",
                "",
            ]
        )
    lines.append("## Acceptance (generator)")
    lines.append("")
    lines.append("All 13 tools emitted; Proposed tools absent.")
    lines.append("")
    return "\n".join(lines)


def hand_tool_sections(hand_text: str) -> dict[str, str]:
    """Map tool name → section body (from ## `name` through next ##)."""
    pattern = re.compile(r"^## `(umst_[a-z_]+)`[^\n]*\n", re.M)
    matches = list(pattern.finditer(hand_text))
    out: dict[str, str] = {}
    for i, m in enumerate(matches):
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(hand_text)
        out[m.group(1)] = hand_text[start:end]
    return out


def section_has_seven_fields(body: str) -> bool:
    return all(re.search(rf"\|\s*{re.escape(f)}\s*\|", body) for f in SEVEN_FIELDS)


def check(tools: list[dict]) -> int:
    hand = HAND.read_text()
    sections = hand_tool_sections(hand)
    names = [t["name"] for t in tools]
    errors: list[str] = []

    for forbidden in PROPOSED_FORBIDDEN:
        if forbidden in names:
            errors.append(f"Proposed tool in generated name set: {forbidden}")
        if forbidden in sections:
            errors.append(f"Proposed tool shipped in hand SSOT heading: {forbidden}")

    for name in names:
        if name not in sections:
            errors.append(f"generated name missing from hand SSOT: {name}")
            continue
        if not section_has_seven_fields(sections[name]):
            errors.append(f"hand SSOT missing 7-field table for {name}")

    # ⊆ : generated ⊆ hand
    extra = set(names) - set(sections)
    if extra:
        errors.append(f"generated not ⊆ hand: {sorted(extra)}")

    if len(names) != 13:
        errors.append(f"expected 13 generated tools, got {len(names)}")

    if errors:
        print("S2 --check FAILED:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    print(f"S2 --check OK: {len(names)} tools ⊆ hand TOOL_CONTRACTS.md with 7-field tables")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="parity check vs hand SSOT")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="write generated fragment")
    ap.add_argument(
        "--write",
        action="store_true",
        help="write fragment even when --check is set",
    )
    args = ap.parse_args()
    tools = load_tools()
    if args.check:
        rc = check(tools)
        if args.write or not args.check:
            pass
        if args.write:
            args.out.write_text(render_fragment(tools))
            print(f"wrote {args.out}")
        return rc
    args.out.write_text(render_fragment(tools))
    print(f"wrote {args.out} ({len(tools)} tools)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
