#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Santosh Prabhu Shenbagamoorthy and Santhosh Shyamsundar
# SPDX-License-Identifier: MIT
"""S2 / go-live Step 1: generate TOOL_CONTRACTS from manifest contracts JSON.

Full 7-field tables for all 13 tools (no hand-SSOT placeholders).
`--check` requires generated == hand (byte-identical after normalize trailing newline).

Usage:
  python3 scripts/gen_tool_contracts.py
  python3 scripts/gen_tool_contracts.py --check
  python3 scripts/gen_tool_contracts.py --write-hand   # sync docs/TOOL_CONTRACTS.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "crates/umst-mcp/src/manifest/tools_v1_schema.json"
CONTRACTS = ROOT / "crates/umst-mcp/src/manifest/tools_v1_contracts.json"
HAND = ROOT / "docs/TOOL_CONTRACTS.md"
DEFAULT_OUT = ROOT / "docs/TOOL_CONTRACTS.generated.md"

SEVEN_FIELDS = (
    "Pre",
    "Post",
    "Errors",
    "Idempotent",
    "SideEffectClass",
    "Cost",
    "Provenance",
)

PROPOSED_FORBIDDEN = (
    "umst_dry_run",
    "umst_promote_contribution",
    "umst_arena_session",
)


def load_schema_tools() -> list[dict]:
    data = json.loads(SCHEMA.read_text())
    tools = data["tools"]
    assert len(tools) == 13, f"expected 13 tools in schema, got {len(tools)}"
    return tools


def load_contracts() -> dict:
    data = json.loads(CONTRACTS.read_text())
    assert data.get("schema_version") == "tools_v1_contracts"
    assert len(data["tool_order"]) == 13
    assert set(data["tool_order"]) == set(data["contracts"])
    return data


def render_document(contracts_doc: dict, schema_tools: list[dict]) -> str:
    schema_names = {t["name"] for t in schema_tools}
    order = contracts_doc["tool_order"]
    missing = set(order) - schema_names
    extra = schema_names - set(order)
    if missing or extra:
        raise SystemExit(f"schema/contracts name mismatch missing={missing} extra={extra}")

    lines: list[str] = [
        "<!-- GENERATED by scripts/gen_tool_contracts.py from tools_v1_contracts.json — do not hand-edit -->",
        "",
        "# MCP tool contracts (B3)",
        "",
        "**Generated from the tool manifest** (`crates/umst-mcp/src/manifest/tools_v1_contracts.json` +",
        "`tools_v1_schema.json`). Go-live Step 1: full 7-field tables for all 13 tools; CI `--check`",
        "requires this file == `docs/TOOL_CONTRACTS.md` (byte-identical).",
        "Index: [`AGENT_MCP.md`](AGENT_MCP.md). Inventory: [`AGENT_SURFACE_AUDIT.md`](AGENT_SURFACE_AUDIT.md).",
        "",
        "Each contract has **seven fields** (table aliases → ToolDescriptor):",
        "",
        "| Alias | Field |",
        "|:---|:---|",
        "| Pre | preconditions |",
        "| Post | postconditions |",
        "| Errors | error taxonomy |",
        "| Idempotent | idempotency |",
        "| SideEffectClass | SideEffectClass |",
        "| Cost | cost |",
        "| Provenance | provenance |",
        "",
        "**SideEffectClass (current mapping / target enum):** `ReadOnly` | `EpistemicMutating` | `NetworkIo` | `Pure` (Proposed names from §5.1).",
        "",
        "---",
        "",
        "## Shared error shapes",
        "",
        "| Shape | When | Remediation |",
        "|:---|:---|:---|",
    ]
    for row in contracts_doc["shared_error_shapes"]:
        lines.append(f"| {row['shape']} | {row['when']} | {row['remediation']} |")
    lines.extend(["", "---", ""])

    for name in order:
        c = contracts_doc["contracts"][name]
        for f in SEVEN_FIELDS:
            if f not in c or not str(c[f]).strip():
                raise SystemExit(f"contract {name} missing field {f}")
            if "See hand" in str(c[f]):
                raise SystemExit(f"contract {name}.{f} still has hand-SSOT placeholder")
        lines.extend(
            [
                f"## `{name}` — {c['title']}",
                "",
                "| Field | Contract |",
                "|:---|:---|",
            ]
        )
        for f in SEVEN_FIELDS:
            lines.append(f"| {f} | {c[f]} |")
        lines.extend(["", c["source"], "", "---", ""])

    lines.extend(
        [
            "## Acceptance",
            "",
            "All 13 tools have the 7 fields; no silent failure; Proposed tools absent from this list.",
            "",
        ]
    )
    return "\n".join(lines)


def normalize(text: str) -> str:
    return text.replace("\r\n", "\n").rstrip() + "\n"


def check(generated: str) -> int:
    hand = normalize(HAND.read_text())
    gen = normalize(generated)
    errors: list[str] = []

    for forbidden in PROPOSED_FORBIDDEN:
        if f"`{forbidden}`" in gen or f"`{forbidden}`" in hand:
            # headings use ## `name`
            if f"## `{forbidden}`" in gen or f"## `{forbidden}`" in hand:
                errors.append(f"Proposed tool shipped: {forbidden}")

    if gen != hand:
        # precise residual delta
        gen_lines = gen.splitlines()
        hand_lines = hand.splitlines()
        max_n = max(len(gen_lines), len(hand_lines))
        diffs = []
        for i in range(max_n):
            g = gen_lines[i] if i < len(gen_lines) else "<EOF>"
            h = hand_lines[i] if i < len(hand_lines) else "<EOF>"
            if g != h:
                diffs.append(f"L{i + 1}: gen={g!r} hand={h!r}")
            if len(diffs) >= 12:
                diffs.append("… (truncated)")
                break
        errors.append("generated != hand TOOL_CONTRACTS.md")
        errors.extend(diffs)

    if errors:
        print("S2 --check FAILED:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    print(
        "S2 --check OK: generated == hand TOOL_CONTRACTS.md "
        f"({len(load_contracts()['tool_order'])} tools, full 7 fields, no placeholders)"
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="require generated == hand")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="write generated doc")
    ap.add_argument(
        "--write-hand",
        action="store_true",
        help="also write docs/TOOL_CONTRACTS.md (sync SSOT to generator output)",
    )
    args = ap.parse_args()

    schema_tools = load_schema_tools()
    contracts_doc = load_contracts()
    generated = normalize(render_document(contracts_doc, schema_tools))

    args.out.write_text(generated)
    print(f"wrote {args.out}")
    if args.write_hand:
        HAND.write_text(generated)
        print(f"wrote {HAND}")

    if args.check:
        return check(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
