// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Santhosh Shyamsundar,
// Santosh Prabhu Shenbagamoorthy — Studio TYTO

#![forbid(unsafe_code)]

//! Deterministic Markdown report of bundled calibration profiles (commit to `docs/Calibration.md`).

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use anyhow::Context;
use sha2::{Digest, Sha256};
use umst_concrete_cartridge::calibration::{Profile, BUNDLED_PROFILE_IDS};

fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    format!("{:x}", h.finalize())
}

fn main() -> anyhow::Result<()> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let profiles_dir = manifest.join("calibration/profiles");

    let mut ids: Vec<&str> = BUNDLED_PROFILE_IDS.to_vec();
    ids.sort_unstable();

    println!("# Calibration report");
    println!();
    println!("Generated by the `calibration_report` binary (`--features cli,calibration`).");
    println!("Keys and sections are sorted for stable diffs.");
    println!();

    println!("## Bundled TOML SHA-256 (UTF-8)");
    println!();
    let mut digests: BTreeMap<&str, String> = BTreeMap::new();
    for id in &ids {
        let path = profiles_dir.join(format!("{id}.v1.toml"));
        let raw = fs::read_to_string(&path)
            .with_context(|| format!("read profile file {}", path.display()))?;
        digests.insert(id, sha256_hex(raw.as_bytes()));
    }
    for (id, d) in &digests {
        println!("- `{id}`: `{d}`");
    }
    println!();

    println!("## Parsed profile summaries");
    println!();
    for id in &ids {
        let p = Profile::load_bundled(id).with_context(|| format!("load bundled `{id}`"))?;
        println!("### `{id}`");
        println!();
        println!("| key | value |");
        println!("|-----|-------|");
        println!("| model_kind | {:?} |", p.model_section.kind);
        println!("| regime.w_c_min | {:.4} |", p.regime.w_c_min);
        println!("| regime.w_c_max | {:.4} |", p.regime.w_c_max);
        println!(
            "| regime.temperature_k_min | {:.4} |",
            p.regime.temperature_k_min
        );
        println!(
            "| regime.temperature_k_max | {:.4} |",
            p.regime.temperature_k_max
        );
        println!("| regime.age_hours_min | {:.4} |", p.regime.age_hours_min);
        println!("| regime.age_hours_max | {:.4} |", p.regime.age_hours_max);
        if let Some(x) = p.regime.fly_ash_pct_max {
            println!("| regime.fly_ash_pct_max | {:.4} |", x);
        }
        if let Some(x) = p.regime.silica_fume_pct_max {
            println!("| regime.silica_fume_pct_max | {:.4} |", x);
        }
        if let Some(x) = p.regime.scm_sum_min_pct {
            println!("| regime.scm_sum_min_pct | {:.4} |", x);
        }
        println!("| powers.s_intrinsic | {:.4} |", p.powers.s_intrinsic);
        println!("| powers.k_slag | {:.4} |", p.powers.k_slag);
        println!("| powers.k_fly_ash | {:.4} |", p.powers.k_fly_ash);
        println!("| powers.k_ref | {:.4} |", p.powers.k_ref);
        println!("| powers.early_boost | {:.4} |", p.powers.early_boost);
        if let Some(x) = p.acceptance.strength_mae_max {
            println!("| acceptance.strength_mae_max | {:.6} |", x);
        }
        if let Some(x) = p.acceptance.strength_rmse_max {
            println!("| acceptance.strength_rmse_max | {:.6} |", x);
        }
        if let Some(x) = p.acceptance.strength_r2_min {
            println!("| acceptance.strength_r2_min | {:.6} |", x);
        }
        println!(
            "| provenance.prototype_3_sha256 | {} |",
            p.provenance.prototype_3_sha256
        );
        println!(
            "| contract.verification_status | {} |",
            p.contract.verification_status
        );
        println!();
    }

    Ok(())
}
